# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
weight = 1
name = "GitHub"
url = "https://github.com/iliaoke"

[social.params]
icon = "brand-github"


[[social]]
identifier = "email"
weight = 2
name = "Email"
url = "mailto:liaoke2007@gmail.com"

[social.params]
icon = "mail"

#[[social]]
#identifier = "twitter"
#weight = 3
#name = "Twitter"
#url = "https://x.com/liaoke321"

#[social.params]
#icon = "brand-twitter"

